FROM node:20.12.0-alpine3.19

WORKDIR /usr/src/app

COPY package.json package-lock.json turbo.json tsconfig.json ./

COPY apps ./apps
COPY packages ./packages

# Install dependencies
RUN npm install
RUN npm run db:generate

# TODO: Filter it down such that you can build and run individual apps
RUN npm run build

CMD ["npm", "run", "start-user-app"]